const swaggerAutogen = require("swagger-autogen")();

const outputFile = "./swagger_output.json";
const endpointsFiles = ["./router.js"];

const doc = {
  info: {
    version: "1.0.0",
    title: "My API",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: "localhost:5000",
  basePath: "/",
  schemes: ["http", "https"],
  consumes: ["application/json"],
  produces: ["application/json"],
  tags: [
    {
      name: "Endpoints",
      description: "User and Product endpoints",
    },
  ],
  securityDefinitions: {
    api_key: {
      type: "apiKey",
      name: "api_key",
      in: "header",
    },
  },
  definitions: {
    UserCredentials: {
      email: "email@email.com",
      password: "123@4",
    },
    User: {
      id: 1,
      name: "Fulano de Tal",
      profession: "Administrador",
      birthDate: "1980-09-29",
      documentNumber: "01234567890",
      phone: "11985476932",
      email: "email@email.com",
      password: "123@4",
      address: {
        zipCode: "42800049",
        street: "Rua Costa Pinto",
        number: 254,
        complement: null,
        neighborhood: "Centro",
        city: "Camaçari",
        state: "BA",
      },
    },
    AddUser: {
      name: "Fulano de Tal",
      profession: "Administrador",
      birthDate: "1980-09-29",
      documentNumber: "01234567890",
      phone: "11985476932",
      email: "email@email.com",
      password: "123@4",
      address: {
        zipCode: "42800049",
        street: "Rua Costa Pinto",
        number: 254,
        complement: null,
        neighborhood: "Centro",
        city: "Camaçari",
        state: "BA",
      },
    },
    Users: [{ $ref: "#/definitions/User" }],
    Product: {
      id: 1,
      name: "Smartphone Sony",
      categoryId: 1,
      price: 1000,
      quantity: 10,
    },
    AddProduct: {
      name: "Smartphone Sony",
      categoryId: 1,
      price: 1000,
      quantity: 10,
    },
    Products: [{ $ref: "#/definitions/Product" }],
  },
};

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require("./app");
});
